name: Release
 
on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ needs.test.result == 'success' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up and cache Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.20.5'
          cache-dependency-path: |
            data-listener/go.sum

      - name: Build and Zip Binaries
        run: |
          cd data-listener
          GOOS=linux GOARCH=amd64 go build -o data_listener_linux_amd64 ./src/cmd/main.go
          tar czf data_listener_linux_amd64.tar.gz data_listener_linux_amd64 ../README.md config.toml examples
          
          GOOS=darwin GOARCH=amd64 go build -o data_listener_darwin_amd64 ./src/cmd/main.go
          tar czf data_listener_darwin_amd64.tar.gz data_listener_darwin_amd64 ../README.md config.toml examples
          
          GOOS=windows GOARCH=amd64 go build -o data_listener_windows_amd64.exe ./src/cmd/main.go
          zip data_listener_windows_amd64.zip data_listener_windows_amd64.exe ../README.md config.toml examples

      - name: Upload All Binaries
        uses: actions/upload-artifact@v4
        with:
          name: all-binaries
          path: |
            data-listener/data_listener_linux_amd64.tar.gz
            data-listener/data_listener_darwin_amd64.tar.gz
            data-listener/data_listener_windows_amd64.zip

  release:
    runs-on: ubuntu-latest
    needs: build
    if: github.event.ref_type == 'tag' && ${{ needs.build.result == 'success' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download All Binaries
        uses: actions/download-artifact@v4
        with:
          name: all-binaries
          path: data-listener

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          body: |
            Release notes for version ${{ github.ref_name }}
          draft: false
          prerelease: false

      - name: Upload Linux Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: data-listener/data_listener_linux_amd64.tar.gz
          asset_name: data_listener_linux_amd64-${{ github.ref_name }}.tar.gz
          asset_content_type: application/zip

      - name: Upload Darwin Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: data-listener/data_listener_darwin_amd64.tar.gz
          asset_name: data_listener_darwin_amd64-${{ github.ref_name }}.tar.gz
          asset_content_type: application/zip

      - name: Upload Windows Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: data-listener/data_listener_windows_amd64.zip
          asset_name: data_listener_windows_amd64-${{ github.ref_name }}.zip
          asset_content_type: application/zip

